name: local
services:
  local-dev01:
    hostname: local-dev01
    container_name: local-dev01
    build:
      context: ../
      dockerfile: local_devcontainer/Dockerfile
    privileged: true
    network_mode: host
    volumes:
      - "local-dev01:/root:rw"
      - "./etc_docker:/etc/docker:r"

volumes:
  local-dev01:
    external: true